"""add_confidence_score_and_fingerprint

Revision ID: 6acec12e9bd4
Revises: 3e8a1b2c3d4f
Create Date: 2026-06-06 21:12:14.115884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acec12e9bd4'
down_revision: Union[str, Sequence[str], None] = '3e8a1b2c3d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('confidence_score', sa.Float(), nullable=True, comment='Confidence score for reconstructed transfers (0.0-1.0)'))
    op.add_column('transfers', sa.Column('fingerprint_hash', sa.String(), nullable=True, comment='Deterministic fingerprint for dedup resolution'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'fingerprint_hash')
    op.drop_column('transfers', 'confidence_score')
    # ### end Alembic commands ###
