"""initial_schema

Revision ID: c667297c9beb
Revises: 
Create Date: 2026-06-04 19:55:18.384734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c667297c9beb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('club_code', sa.String(), nullable=True),
    sa.Column('domestic_competition_id', sa.String(), nullable=True),
    sa.Column('total_transfers', sa.Integer(), nullable=True),
    sa.Column('median_roi', sa.Float(), nullable=True),
    sa.Column('annualized_roi', sa.Float(), nullable=True),
    sa.Column('total_profit', sa.Float(), nullable=True),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('value_creation', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('club_id')
    )
    op.create_table('player_valuations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('market_value_in_eur', sa.Float(), nullable=True),
    sa.Column('current_club_id', sa.Integer(), nullable=True),
    sa.Column('current_club_name', sa.String(), nullable=True),
    sa.Column('player_club_domestic_competition_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('sub_position', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('current_club_id', sa.Integer(), nullable=True),
    sa.Column('current_club_name', sa.String(), nullable=True),
    sa.Column('foot', sa.String(), nullable=True),
    sa.Column('height_in_cm', sa.Float(), nullable=True),
    sa.Column('market_value_in_eur', sa.Float(), nullable=True),
    sa.Column('highest_market_value_in_eur', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('transfers',
    sa.Column('transfer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('from_club_id', sa.Integer(), nullable=True),
    sa.Column('to_club_id', sa.Integer(), nullable=True),
    sa.Column('from_club_name', sa.String(), nullable=True),
    sa.Column('to_club_name', sa.String(), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.Column('transfer_season', sa.String(), nullable=True),
    sa.Column('transfer_fee', sa.Float(), nullable=True),
    sa.Column('market_value_in_eur', sa.Float(), nullable=True),
    sa.Column('buy_fee', sa.Float(), nullable=True),
    sa.Column('sell_fee', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('roi_pct', sa.Float(), nullable=True),
    sa.Column('annualized_roi_pct', sa.Float(), nullable=True),
    sa.Column('tenure_days', sa.Integer(), nullable=True),
    sa.Column('tenure_years', sa.Float(), nullable=True),
    sa.Column('peak_value', sa.Float(), nullable=True),
    sa.Column('value_creation_pct', sa.Float(), nullable=True),
    sa.Column('player_position', sa.String(), nullable=True),
    sa.Column('age_at_transfer', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers')
    op.drop_table('players')
    op.drop_table('player_valuations')
    op.drop_table('clubs')
    # ### end Alembic commands ###
