"""add_confidence_reasons

Revision ID: e1a4a5605f5b
Revises: 6acec12e9bd4
Create Date: 2026-06-06 21:15:04.664290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a4a5605f5b'
down_revision: Union[str, Sequence[str], None] = '6acec12e9bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('confidence_reasons', sa.String(), nullable=True, comment='JSON-serialized list of confidence reason strings'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'confidence_reasons')
    # ### end Alembic commands ###
